### ISSUE TITLE
Make hardware cursor customizable

### ISSUE THREAD

**Issue by Darnagof** [ObEngine/ObEngine#290]
Currently, the cursor appearance can be modified by making a software cursor (updating a sprite at cursor position at each frame). But this cursor has latency compared to the hardware one.

**Comment by Sygmei** [comment]
SFML already has what we need to implement this feature : https://www.sfml-dev.org/documentation/2.5.1/classsf_1_1Cursor.php
We just need to create a proxy class

**Comment by Sygmei** [comment]
Done in https://github.com/ObEngine/ObEngine/pull/376
