### ISSUE TITLE
SVG support for ÖbEngine

### ISSUE THREAD

**Issue by Sygmei** [ObEngine/ObEngine#312]
ÖbEngine only supports bitmap formats for now through the SFML library.
It would be nice to have SVG support (with a library that converts SVG to a Texture which will then be usable for example).
I know two potentials libraries that could do the job but do not hesitate to suggest another one : 
- https://github.com/memononen/nanosvg
- https://github.com/sammycage/lunasvg

Place to look at : [src/Core/Graphics/Texture.cpp](https://github.com/Sygmei/ObEngine/blob/master/src/Core/Graphics/Texture.cpp)

**Comment by nfarid** [comment]
I've sent a pull request: https://github.com/Sygmei/ObEngine/pull/354

**Comment by Sygmei** [comment]
Done in #354
