### ISSUE TITLE
Don't set over to true for Chronometer if it has never been started

### ISSUE THREAD

**Issue by Sygmei** [ObEngine/ObEngine#336]
Currently, the `over()` method of the `Chronometer` class returns true even if the Chronometer was never started.
To know if the Chronometer is started or not we could also a `started` method

## Where to look at ?
- [include/Core/Time/Chronometer.hpp](https://github.com/ObEngine/ObEngine/blob/master/include/Core/Time/Chronometer.hpp)
- [src/Core/Time/Chronometer.cpp](https://github.com/ObEngine/ObEngine/blob/master/src/Core/Time/Chronometer.cpp)
- [src/Core/Bindings/obe/Time/Time.cpp](https://github.com/ObEngine/ObEngine/blob/master/src/Core/Bindings/obe/Time/Time.cpp)

**Comment by hexqwit** [comment]
I looked at the specified files. And have a bit of understanding of what's going on! But I'm not sure about how I should approach the issue at hand. So, we just need a `started` method, that sets to true if `m_started` is true?

**Comment by Sygmei** [comment]
Yes @hexqwit exactly, also `over()` should not return `true` if `m_started` is not `true`

**Comment by Sygmei** [comment]
Done in https://github.com/ObEngine/ObEngine/pull/366
